import 'package:currency_pickers/country.dart';

final List<Country> kcountryList = [
  Country(
    isoCode: "AF",
    currencyCode: "AFN",
    currencyName: "Afghan afghani",
    name: "Afghanistan",
    iso3Code: "AFG",
  ),
  Country(
    isoCode: "AX",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Åland Islands",
    iso3Code: "ALA",
  ),
  Country(
    isoCode: "AL",
    currencyCode: "ALL",
    currencyName: "Albanian lek",
    name: "Albania",
    iso3Code: "ALB",
  ),
  Country(
    isoCode: "DZ",
    currencyCode: "DZD",
    currencyName: "Algerian dinar",
    name: "Algeria",
    iso3Code: "DZA",
  ),
  Country(
    isoCode: "AS",
    currencyCode: "USD",
    currencyName: "United State Dollar",
    name: "American Samoa",
    iso3Code: "ASM",
  ),
  Country(
    isoCode: "AD",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Andorra",
    iso3Code: "AND",
  ),
  Country(
    isoCode: "AO",
    currencyCode: "AOA",
    currencyName: "Angolan kwanza",
    name: "Angola",
    iso3Code: "AGO",
  ),
  Country(
    isoCode: "AI",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Anguilla",
    iso3Code: "AIA",
  ),
  Country(
    isoCode: "AQ",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Antarctica",
    iso3Code: "ATA",
  ),
  Country(
    isoCode: "AG",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Antigua and Barbuda",
    iso3Code: "ATG",
  ),
  Country(
    isoCode: "AR",
    currencyCode: "ARS",
    currencyName: "Argentine peso",
    name: "Argentina",
    iso3Code: "ARG",
  ),
  Country(
    isoCode: "AM",
    currencyCode: "AMD",
    currencyName: "Armenian dram",
    name: "Armenia",
    iso3Code: "ARM",
  ),
  Country(
    isoCode: "AW",
    currencyCode: "AWG",
    currencyName: "Aruban florin",
    name: "Aruba",
    iso3Code: "ABW",
  ),
  Country(
    isoCode: "AU",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Australia",
    iso3Code: "AUS",
  ),
  Country(
    isoCode: "AT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Austria",
    iso3Code: "AUT",
  ),
  Country(
    isoCode: "AZ",
    currencyCode: "AZN",
    currencyName: "Azerbaijani manat",
    name: "Azerbaijan",
    iso3Code: "AZE",
  ),
  Country(
    isoCode: "BS",
    currencyCode: "BSD",
    currencyName: "Bahamian dollar",
    name: "Bahamas",
    iso3Code: "BHS",
  ),
  Country(
    isoCode: "BH",
    currencyCode: "BHD",
    currencyName: "Bahraini dinar",
    name: "Bahrain",
    iso3Code: "BHR",
  ),
  Country(
    isoCode: "BD",
    currencyCode: "BDT",
    currencyName: "Bangladeshi taka",
    name: "Bangladesh",
    iso3Code: "BGD",
  ),
  Country(
    isoCode: "BB",
    currencyCode: "BBD",
    currencyName: "Barbadian dollar",
    name: "Barbados",
    iso3Code: "BRB",
  ),
  Country(
    isoCode: "BY",
    currencyCode: "BYN",
    currencyName: "New Belarusian ruble",
    name: "Belarus",
    iso3Code: "BLR",
  ),
  Country(
    isoCode: "BE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Belgium",
    iso3Code: "BEL",
  ),
  Country(
    isoCode: "BZ",
    currencyCode: "BZD",
    currencyName: "Belize dollar",
    name: "Belize",
    iso3Code: "BLZ",
  ),
  Country(
    isoCode: "BJ",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Benin",
    iso3Code: "BEN",
  ),
  Country(
    isoCode: "BM",
    currencyCode: "BMD",
    currencyName: "Bermudian dollar",
    name: "Bermuda",
    iso3Code: "BMU",
  ),
  Country(
    isoCode: "BT",
    currencyCode: "BTN",
    currencyName: "Bhutanese ngultrum",
    name: "Bhutan",
    iso3Code: "BTN",
  ),
  Country(
    isoCode: "BO",
    currencyCode: "BOB",
    currencyName: "Bolivian boliviano",
    name: "Bolivia (Plurinational State of)",
    iso3Code: "BOL",
  ),
  Country(
    isoCode: "BQ",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Bonaire, Sint Eustatius and Saba",
    iso3Code: "BES",
  ),
  Country(
    isoCode: "BA",
    currencyCode: "BAM",
    currencyName: "Bosnia and Herzegovina convertible mark",
    name: "Bosnia and Herzegovina",
    iso3Code: "BIH",
  ),
  Country(
    isoCode: "BW",
    currencyCode: "BWP",
    currencyName: "Botswana pula",
    name: "Botswana",
    iso3Code: "BWA",
  ),
  Country(
    isoCode: "BV",
    currencyCode: "NOK",
    currencyName: "Norwegian krone",
    name: "Bouvet Island",
    iso3Code: "BVT",
  ),
  Country(
    isoCode: "BR",
    currencyCode: "BRL",
    currencyName: "Brazilian real",
    name: "Brazil",
    iso3Code: "BRA",
  ),
  Country(
    isoCode: "IO",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "British Indian Ocean Territory",
    iso3Code: "IOT",
  ),
  Country(
    isoCode: "VG",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Virgin Islands (British)",
    iso3Code: "VGB",
  ),
  Country(
    isoCode: "VI",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Virgin Islands (U.S.)",
    iso3Code: "VIR",
  ),
  Country(
    isoCode: "BN",
    currencyCode: "BND",
    currencyName: "Brunei dollar",
    name: "Brunei Darussalam",
    iso3Code: "BRN",
  ),
  Country(
    isoCode: "BG",
    currencyCode: "BGN",
    currencyName: "Bulgarian lev",
    name: "Bulgaria",
    iso3Code: "BGR",
  ),
  Country(
    isoCode: "BF",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Burkina Faso",
    iso3Code: "BFA",
  ),
  Country(
    isoCode: "BI",
    currencyCode: "BIF",
    currencyName: "Burundian franc",
    name: "Burundi",
    iso3Code: "BDI",
  ),
  Country(
    isoCode: "KH",
    currencyCode: "KHR",
    currencyName: "Cambodian riel",
    name: "Cambodia",
    iso3Code: "KHM",
  ),
  Country(
    isoCode: "CM",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Cameroon",
    iso3Code: "CMR",
  ),
  Country(
    isoCode: "CA",
    currencyCode: "CAD",
    currencyName: "Canadian dollar",
    name: "Canada",
    iso3Code: "CAN",
  ),
  Country(
    isoCode: "CV",
    currencyCode: "CVE",
    currencyName: "Cape Verdean escudo",
    name: "Cabo Verde",
    iso3Code: "CPV",
  ),
  Country(
    isoCode: "KY",
    currencyCode: "KYD",
    currencyName: "Cayman Islands dollar",
    name: "Cayman Islands",
    iso3Code: "CYM",
  ),
  Country(
    isoCode: "CF",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Central African Republic",
    iso3Code: "CAF",
  ),
  Country(
    isoCode: "TD",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Chad",
    iso3Code: "TCD",
  ),
  Country(
    isoCode: "CL",
    currencyCode: "CLP",
    currencyName: "Chilean peso",
    name: "Chile",
    iso3Code: "CHL",
  ),
  Country(
    isoCode: "CN",
    currencyCode: "CNY",
    currencyName: "Chinese yuan",
    name: "China",
    iso3Code: "CHN",
  ),
  Country(
    isoCode: "CX",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Christmas Island",
    iso3Code: "CXR",
  ),
  Country(
    isoCode: "CC",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Cocos (Keeling) Islands",
    iso3Code: "CCK",
  ),
  Country(
    isoCode: "CO",
    currencyCode: "COP",
    currencyName: "Colombian peso",
    name: "Colombia",
    iso3Code: "COL",
  ),
  Country(
    isoCode: "KM",
    currencyCode: "KMF",
    currencyName: "Comorian franc",
    name: "Comoros",
    iso3Code: "COM",
  ),
  Country(
    isoCode: "CG",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Congo",
    iso3Code: "COG",
  ),
  Country(
    isoCode: "CD",
    currencyCode: "CDF",
    currencyName: "Congolese franc",
    name: "Congo (Democratic Republic of the)",
    iso3Code: "COD",
  ),
  Country(
    isoCode: "CK",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Cook Islands",
    iso3Code: "COK",
  ),
  Country(
    isoCode: "CR",
    currencyCode: "CRC",
    currencyName: "Costa Rican colón",
    name: "Costa Rica",
    iso3Code: "CRI",
  ),
  Country(
    isoCode: "HR",
    currencyCode: "HRK",
    currencyName: "Croatian kuna",
    name: "Croatia",
    iso3Code: "HRV",
  ),
  Country(
    isoCode: "CU",
    currencyCode: "CUC",
    currencyName: "Cuban convertible peso",
    name: "Cuba",
    iso3Code: "CUB",
  ),
  Country(
    isoCode: "CW",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean guilder",
    name: "Curaçao",
    iso3Code: "CUW",
  ),
  Country(
    isoCode: "CY",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Cyprus",
    iso3Code: "CYP",
  ),
  Country(
    isoCode: "CZ",
    currencyCode: "CZK",
    currencyName: "Czech koruna",
    name: "Czech Republic",
    iso3Code: "CZE",
  ),
  Country(
    isoCode: "DK",
    currencyCode: "DKK",
    currencyName: "Danish krone",
    name: "Denmark",
    iso3Code: "DNK",
  ),
  Country(
    isoCode: "DJ",
    currencyCode: "DJF",
    currencyName: "Djiboutian franc",
    name: "Djibouti",
    iso3Code: "DJI",
  ),
  Country(
    isoCode: "DM",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Dominica",
    iso3Code: "DMA",
  ),
  Country(
    isoCode: "DO",
    currencyCode: "DOP",
    currencyName: "Dominican peso",
    name: "Dominican Republic",
    iso3Code: "DOM",
  ),
  Country(
    isoCode: "EC",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Ecuador",
    iso3Code: "ECU",
  ),
  Country(
    isoCode: "EG",
    currencyCode: "EGP",
    currencyName: "Egyptian pound",
    name: "Egypt",
    iso3Code: "EGY",
  ),
  Country(
    isoCode: "SV",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "El Salvador",
    iso3Code: "SLV",
  ),
  Country(
    isoCode: "GQ",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Equatorial Guinea",
    iso3Code: "GNQ",
  ),
  Country(
    isoCode: "ER",
    currencyCode: "ERN",
    currencyName: "Eritrean nakfa",
    name: "Eritrea",
    iso3Code: "ERI",
  ),
  Country(
    isoCode: "EE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Estonia",
    iso3Code: "EST",
  ),
  Country(
    isoCode: "ET",
    currencyCode: "ETB",
    currencyName: "Ethiopian birr",
    name: "Ethiopia",
    iso3Code: "ETH",
  ),
  Country(
    isoCode: "FK",
    currencyCode: "FKP",
    currencyName: "Falkland Islands pound",
    name: "Falkland Islands (Malvinas)",
    iso3Code: "FLK",
  ),
  Country(
    isoCode: "FO",
    currencyCode: "DKK",
    currencyName: "Danish krone",
    name: "Faroe Islands",
    iso3Code: "FRO",
  ),
  Country(
    isoCode: "FJ",
    currencyCode: "FJD",
    currencyName: "Fijian dollar",
    name: "Fiji",
    iso3Code: "FJI",
  ),
  Country(
    isoCode: "FI",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Finland",
    iso3Code: "FIN",
  ),
  Country(
    isoCode: "FR",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "France",
    iso3Code: "FRA",
  ),
  Country(
    isoCode: "GF",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "French Guiana",
    iso3Code: "GUF",
  ),
  Country(
    isoCode: "PF",
    currencyCode: "XPF",
    currencyName: "CFP franc",
    name: "French Polynesia",
    iso3Code: "PYF",
  ),
  Country(
    isoCode: "TF",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "French Southern Territories",
    iso3Code: "ATF",
  ),
  Country(
    isoCode: "GA",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Gabon",
    iso3Code: "GAB",
  ),
  Country(
    isoCode: "GM",
    currencyCode: "GMD",
    currencyName: "Gambian dalasi",
    name: "Gambia",
    iso3Code: "GMB",
  ),
  Country(
    isoCode: "GE",
    currencyCode: "GEL",
    currencyName: "Georgian Lari",
    name: "Georgia",
    iso3Code: "GEO",
  ),
  Country(
    isoCode: "DE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Germany",
    iso3Code: "DEU",
  ),
  Country(
    isoCode: "GH",
    currencyCode: "GHS",
    currencyName: "Ghanaian cedi",
    name: "Ghana",
    iso3Code: "GHA",
  ),
  Country(
    isoCode: "GI",
    currencyCode: "GIP",
    currencyName: "Gibraltar pound",
    name: "Gibraltar",
    iso3Code: "GIB",
  ),
  Country(
    isoCode: "GR",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Greece",
    iso3Code: "GRC",
  ),
  Country(
    isoCode: "GL",
    currencyCode: "DKK",
    currencyName: "Danish krone",
    name: "Greenland",
    iso3Code: "GRL",
  ),
  Country(
    isoCode: "GD",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Grenada",
    iso3Code: "GRD",
  ),
  Country(
    isoCode: "GP",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Guadeloupe",
    iso3Code: "GLP",
  ),
  Country(
    isoCode: "GU",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Guam",
    iso3Code: "GUM",
  ),
  Country(
    isoCode: "GT",
    currencyCode: "GTQ",
    currencyName: "Guatemalan quetzal",
    name: "Guatemala",
    iso3Code: "GTM",
  ),
  Country(
    isoCode: "GG",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "Guernsey",
    iso3Code: "GGY",
  ),
  Country(
    isoCode: "GN",
    currencyCode: "GNF",
    currencyName: "Guinean franc",
    name: "Guinea",
    iso3Code: "GIN",
  ),
  Country(
    isoCode: "GW",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Guinea-Bissau",
    iso3Code: "GNB",
  ),
  Country(
    isoCode: "GY",
    currencyCode: "GYD",
    currencyName: "Guyanese dollar",
    name: "Guyana",
    iso3Code: "GUY",
  ),
  Country(
    isoCode: "HT",
    currencyCode: "HTG",
    currencyName: "Haitian gourde",
    name: "Haiti",
    iso3Code: "HTI",
  ),
  Country(
    isoCode: "HM",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Heard Island and McDonald Islands",
    iso3Code: "HMD",
  ),
  Country(
    isoCode: "VA",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Holy See",
    iso3Code: "VAT",
  ),
  Country(
    isoCode: "HN",
    currencyCode: "HNL",
    currencyName: "Honduran lempira",
    name: "Honduras",
    iso3Code: "HND",
  ),
  Country(
    isoCode: "HK",
    currencyCode: "HKD",
    currencyName: "Hong Kong dollar",
    name: "Hong Kong",
    iso3Code: "HKG",
  ),
  Country(
    isoCode: "HU",
    currencyCode: "HUF",
    currencyName: "Hungarian forint",
    name: "Hungary",
    iso3Code: "HUN",
  ),
  Country(
    isoCode: "IS",
    currencyCode: "ISK",
    currencyName: "Icelandic króna",
    name: "Iceland",
    iso3Code: "ISL",
  ),
  Country(
    isoCode: "IN",
    currencyCode: "INR",
    currencyName: "Indian rupee",
    name: "India",
    iso3Code: "IND",
  ),
  Country(
    isoCode: "ID",
    currencyCode: "IDR",
    currencyName: "Indonesian rupiah",
    name: "Indonesia",
    iso3Code: "IDN",
  ),
  Country(
    isoCode: "CI",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Côte d'Ivoire",
    iso3Code: "CIV",
  ),
  Country(
    isoCode: "IR",
    currencyCode: "IRR",
    currencyName: "Iranian rial",
    name: "Iran (Islamic Republic of)",
    iso3Code: "IRN",
  ),
  Country(
    isoCode: "IQ",
    currencyCode: "IQD",
    currencyName: "Iraqi dinar",
    name: "Iraq",
    iso3Code: "IRQ",
  ),
  Country(
    isoCode: "IE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Ireland",
    iso3Code: "IRL",
  ),
  Country(
    isoCode: "IM",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "Isle of Man",
    iso3Code: "IMN",
  ),
  Country(
    isoCode: "IL",
    currencyCode: "ILS",
    currencyName: "Israeli new shekel",
    name: "Israel",
    iso3Code: "ISR",
  ),
  Country(
    isoCode: "IT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Italy",
    iso3Code: "ITA",
  ),
  Country(
    isoCode: "JM",
    currencyCode: "JMD",
    currencyName: "Jamaican dollar",
    name: "Jamaica",
    iso3Code: "JAM",
  ),
  Country(
    isoCode: "JP",
    currencyCode: "JPY",
    currencyName: "Japanese yen",
    name: "Japan",
    iso3Code: "JPN",
  ),
  Country(
    isoCode: "JE",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "Jersey",
    iso3Code: "JEY",
  ),
  Country(
    isoCode: "JO",
    currencyCode: "JOD",
    currencyName: "Jordanian dinar",
    name: "Jordan",
    iso3Code: "JOR",
  ),
  Country(
    isoCode: "KZ",
    currencyCode: "KZT",
    currencyName: "Kazakhstani tenge",
    name: "Kazakhstan",
    iso3Code: "KAZ",
  ),
  Country(
    isoCode: "KE",
    currencyCode: "KES",
    currencyName: "Kenyan shilling",
    name: "Kenya",
    iso3Code: "KEN",
  ),
  Country(
    isoCode: "KI",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Kiribati",
    iso3Code: "KIR",
  ),
  Country(
    isoCode: "KW",
    currencyCode: "KWD",
    currencyName: "Kuwaiti dinar",
    name: "Kuwait",
    iso3Code: "KWT",
  ),
  Country(
    isoCode: "KG",
    currencyCode: "KGS",
    currencyName: "Kyrgyzstani som",
    name: "Kyrgyzstan",
    iso3Code: "KGZ",
  ),
  Country(
    isoCode: "LA",
    currencyCode: "LAK",
    currencyName: "Lao kip",
    name: "Lao People's Democratic Republic",
    iso3Code: "LAO",
  ),
  Country(
    isoCode: "LV",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Latvia",
    iso3Code: "LVA",
  ),
  Country(
    isoCode: "LB",
    currencyCode: "LBP",
    currencyName: "Lebanese pound",
    name: "Lebanon",
    iso3Code: "LBN",
  ),
  Country(
    isoCode: "LS",
    currencyCode: "LSL",
    currencyName: "Lesotho loti",
    name: "Lesotho",
    iso3Code: "LSO",
  ),
  Country(
    isoCode: "LR",
    currencyCode: "LRD",
    currencyName: "Liberian dollar",
    name: "Liberia",
    iso3Code: "LBR",
  ),
  Country(
    isoCode: "LY",
    currencyCode: "LYD",
    currencyName: "Libyan dinar",
    name: "Libya",
    iso3Code: "LBY",
  ),
  Country(
    isoCode: "LI",
    currencyCode: "CHF",
    currencyName: "Swiss franc",
    name: "Liechtenstein",
    iso3Code: "LIE",
  ),
  Country(
    isoCode: "LT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Lithuania",
    iso3Code: "LTU",
  ),
  Country(
    isoCode: "LU",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Luxembourg",
    iso3Code: "LUX",
  ),
  Country(
    isoCode: "MO",
    currencyCode: "MOP",
    currencyName: "Macanese pataca",
    name: "Macao",
    iso3Code: "MAC",
  ),
  Country(
    isoCode: "MK",
    currencyCode: "MKD",
    currencyName: "Macedonian denar",
    name: "Macedonia (the former Yugoslav Republic of)",
    iso3Code: "MKD",
  ),
  Country(
    isoCode: "MG",
    currencyCode: "MGA",
    currencyName: "Malagasy ariary",
    name: "Madagascar",
    iso3Code: "MDG",
  ),
  Country(
    isoCode: "MW",
    currencyCode: "MWK",
    currencyName: "Malawian kwacha",
    name: "Malawi",
    iso3Code: "MWI",
  ),
  Country(
    isoCode: "MY",
    currencyCode: "MYR",
    currencyName: "Malaysian ringgit",
    name: "Malaysia",
    iso3Code: "MYS",
  ),
  Country(
    isoCode: "MV",
    currencyCode: "MVR",
    currencyName: "Maldivian rufiyaa",
    name: "Maldives",
    iso3Code: "MDV",
  ),
  Country(
    isoCode: "ML",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Mali",
    iso3Code: "MLI",
  ),
  Country(
    isoCode: "MT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Malta",
    iso3Code: "MLT",
  ),
  Country(
    isoCode: "MH",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Marshall Islands",
    iso3Code: "MHL",
  ),
  Country(
    isoCode: "MQ",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Martinique",
    iso3Code: "MTQ",
  ),
  Country(
    isoCode: "MR",
    currencyCode: "MRO",
    currencyName: "Mauritanian ouguiya",
    name: "Mauritania",
    iso3Code: "MRT",
  ),
  Country(
    isoCode: "MU",
    currencyCode: "MUR",
    currencyName: "Mauritian rupee",
    name: "Mauritius",
    iso3Code: "MUS",
  ),
  Country(
    isoCode: "YT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Mayotte",
    iso3Code: "MYT",
  ),
  Country(
    isoCode: "MX",
    currencyCode: "MXN",
    currencyName: "Mexican peso",
    name: "Mexico",
    iso3Code: "MEX",
  ),
  Country(
    isoCode: "FM",
    currencyCode: "None",
    currencyName: "[D]",
    name: "Micronesia (Federated States of)",
    iso3Code: "FSM",
  ),
  Country(
    isoCode: "MD",
    currencyCode: "MDL",
    currencyName: "Moldovan leu",
    name: "Moldova (Republic of)",
    iso3Code: "MDA",
  ),
  Country(
    isoCode: "MC",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Monaco",
    iso3Code: "MCO",
  ),
  Country(
    isoCode: "MN",
    currencyCode: "MNT",
    currencyName: "Mongolian tögrög",
    name: "Mongolia",
    iso3Code: "MNG",
  ),
  Country(
    isoCode: "ME",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Montenegro",
    iso3Code: "MNE",
  ),
  Country(
    isoCode: "MS",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Montserrat",
    iso3Code: "MSR",
  ),
  Country(
    isoCode: "MA",
    currencyCode: "MAD",
    currencyName: "Moroccan dirham",
    name: "Morocco",
    iso3Code: "MAR",
  ),
  Country(
    isoCode: "MZ",
    currencyCode: "MZN",
    currencyName: "Mozambican metical",
    name: "Mozambique",
    iso3Code: "MOZ",
  ),
  Country(
    isoCode: "MM",
    currencyCode: "MMK",
    currencyName: "Burmese kyat",
    name: "Myanmar",
    iso3Code: "MMR",
  ),
  Country(
    isoCode: "NA",
    currencyCode: "NAD",
    currencyName: "Namibian dollar",
    name: "Namibia",
    iso3Code: "NAM",
  ),
  Country(
    isoCode: "NR",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Nauru",
    iso3Code: "NRU",
  ),
  Country(
    isoCode: "NP",
    currencyCode: "NPR",
    currencyName: "Nepalese rupee",
    name: "Nepal",
    iso3Code: "NPL",
  ),
  Country(
    isoCode: "NL",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Netherlands",
    iso3Code: "NLD",
  ),
  Country(
    isoCode: "NC",
    currencyCode: "XPF",
    currencyName: "CFP franc",
    name: "New Caledonia",
    iso3Code: "NCL",
  ),
  Country(
    isoCode: "NZ",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "New Zealand",
    iso3Code: "NZL",
  ),
  Country(
    isoCode: "NI",
    currencyCode: "NIO",
    currencyName: "Nicaraguan córdoba",
    name: "Nicaragua",
    iso3Code: "NIC",
  ),
  Country(
    isoCode: "NE",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Niger",
    iso3Code: "NER",
  ),
  Country(
    isoCode: "NG",
    currencyCode: "NGN",
    currencyName: "Nigerian naira",
    name: "Nigeria",
    iso3Code: "NGA",
  ),
  Country(
    isoCode: "NU",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Niue",
    iso3Code: "NIU",
  ),
  Country(
    isoCode: "NF",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Norfolk Island",
    iso3Code: "NFK",
  ),
  Country(
    isoCode: "KP",
    currencyCode: "KPW",
    currencyName: "North Korean won",
    name: "Korea (Democratic People's Republic of)",
    iso3Code: "PRK",
  ),
  Country(
    isoCode: "MP",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Northern Mariana Islands",
    iso3Code: "MNP",
  ),
  Country(
    isoCode: "NO",
    currencyCode: "NOK",
    currencyName: "Norwegian krone",
    name: "Norway",
    iso3Code: "NOR",
  ),
  Country(
    isoCode: "OM",
    currencyCode: "OMR",
    currencyName: "Omani rial",
    name: "Oman",
    iso3Code: "OMN",
  ),
  Country(
    isoCode: "PK",
    currencyCode: "PKR",
    currencyName: "Pakistani rupee",
    name: "Pakistan",
    iso3Code: "PAK",
  ),
  Country(
    isoCode: "PW",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Palau",
    iso3Code: "PLW",
  ),
  Country(
    isoCode: "PS",
    currencyCode: "ILS",
    currencyName: "Israeli new sheqel",
    name: "Palestine, State of",
    iso3Code: "PSE",
  ),
  Country(
    isoCode: "PA",
    currencyCode: "PAB",
    currencyName: "Panamanian balboa",
    name: "Panama",
    iso3Code: "PAN",
  ),
  Country(
    isoCode: "PG",
    currencyCode: "PGK",
    currencyName: "Papua New Guinean kina",
    name: "Papua New Guinea",
    iso3Code: "PNG",
  ),
  Country(
    isoCode: "PY",
    currencyCode: "PYG",
    currencyName: "Paraguayan guaraní",
    name: "Paraguay",
    iso3Code: "PRY",
  ),
  Country(
    isoCode: "PE",
    currencyCode: "PEN",
    currencyName: "Peruvian sol",
    name: "Peru",
    iso3Code: "PER",
  ),
  Country(
    isoCode: "PH",
    currencyCode: "PHP",
    currencyName: "Philippine peso",
    name: "Philippines",
    iso3Code: "PHL",
  ),
  Country(
    isoCode: "PN",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Pitcairn",
    iso3Code: "PCN",
  ),
  Country(
    isoCode: "PL",
    currencyCode: "PLN",
    currencyName: "Polish złoty",
    name: "Poland",
    iso3Code: "POL",
  ),
  Country(
    isoCode: "PT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Portugal",
    iso3Code: "PRT",
  ),
  Country(
    isoCode: "PR",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Puerto Rico",
    iso3Code: "PRI",
  ),
  Country(
    isoCode: "QA",
    currencyCode: "QAR",
    currencyName: "Qatari riyal",
    name: "Qatar",
    iso3Code: "QAT",
  ),
  Country(
    isoCode: "XK",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Republic of Kosovo",
    iso3Code: "KOS",
  ),
  Country(
    isoCode: "RE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Réunion",
    iso3Code: "REU",
  ),
  Country(
    isoCode: "RO",
    currencyCode: "RON",
    currencyName: "Romanian leu",
    name: "Romania",
    iso3Code: "ROU",
  ),
  Country(
    isoCode: "RU",
    currencyCode: "RUB",
    currencyName: "Russian ruble",
    name: "Russian Federation",
    iso3Code: "RUS",
  ),
  Country(
    isoCode: "RW",
    currencyCode: "RWF",
    currencyName: "Rwandan franc",
    name: "Rwanda",
    iso3Code: "RWA",
  ),
  Country(
    isoCode: "BL",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Saint Barthélemy",
    iso3Code: "BLM",
  ),
  Country(
    isoCode: "SH",
    currencyCode: "SHP",
    currencyName: "Saint Helena pound",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    iso3Code: "SHN",
  ),
  Country(
    isoCode: "KN",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Saint Kitts and Nevis",
    iso3Code: "KNA",
  ),
  Country(
    isoCode: "LC",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Saint Lucia",
    iso3Code: "LCA",
  ),
  Country(
    isoCode: "MF",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Saint Martin (French part)",
    iso3Code: "MAF",
  ),
  Country(
    isoCode: "PM",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Saint Pierre and Miquelon",
    iso3Code: "SPM",
  ),
  Country(
    isoCode: "VC",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Saint Vincent and the Grenadines",
    iso3Code: "VCT",
  ),
  Country(
    isoCode: "WS",
    currencyCode: "WST",
    currencyName: "Samoan tālā",
    name: "Samoa",
    iso3Code: "WSM",
  ),
  Country(
    isoCode: "SM",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "San Marino",
    iso3Code: "SMR",
  ),
  Country(
    isoCode: "ST",
    currencyCode: "STD",
    currencyName: "São Tomé and Príncipe dobra",
    name: "Sao Tome and Principe",
    iso3Code: "STP",
  ),
  Country(
    isoCode: "SA",
    currencyCode: "SAR",
    currencyName: "Saudi riyal",
    name: "Saudi Arabia",
    iso3Code: "SAU",
  ),
  Country(
    isoCode: "SN",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Senegal",
    iso3Code: "SEN",
  ),
  Country(
    isoCode: "RS",
    currencyCode: "RSD",
    currencyName: "Serbian dinar",
    name: "Serbia",
    iso3Code: "SRB",
  ),
  Country(
    isoCode: "SC",
    currencyCode: "SCR",
    currencyName: "Seychellois rupee",
    name: "Seychelles",
    iso3Code: "SYC",
  ),
  Country(
    isoCode: "SL",
    currencyCode: "SLL",
    currencyName: "Sierra Leonean leone",
    name: "Sierra Leone",
    iso3Code: "SLE",
  ),
  Country(
    isoCode: "SG",
    currencyCode: "SGD",
    currencyName: "Singapore dollar",
    name: "Singapore",
    iso3Code: "SGP",
  ),
  Country(
    isoCode: "SX",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean guilder",
    name: "Sint Maarten (Dutch part)",
    iso3Code: "SXM",
  ),
  Country(
    isoCode: "SK",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Slovakia",
    iso3Code: "SVK",
  ),
  Country(
    isoCode: "SI",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Slovenia",
    iso3Code: "SVN",
  ),
  Country(
    isoCode: "SB",
    currencyCode: "SBD",
    currencyName: "Solomon Islands dollar",
    name: "Solomon Islands",
    iso3Code: "SLB",
  ),
  Country(
    isoCode: "SO",
    currencyCode: "SOS",
    currencyName: "Somali shilling",
    name: "Somalia",
    iso3Code: "SOM",
  ),
  Country(
    isoCode: "ZA",
    currencyCode: "ZAR",
    currencyName: "South African rand",
    name: "South Africa",
    iso3Code: "ZAF",
  ),
  Country(
    isoCode: "GS",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "South Georgia and the South Sandwich Islands",
    iso3Code: "SGS",
  ),
  Country(
    isoCode: "KR",
    currencyCode: "KRW",
    currencyName: "South Korean won",
    name: "Korea (Republic of)",
    iso3Code: "KOR",
  ),
  Country(
    isoCode: "SS",
    currencyCode: "SSP",
    currencyName: "South Sudanese pound",
    name: "South Sudan",
    iso3Code: "SSD",
  ),
  Country(
    isoCode: "ES",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Spain",
    iso3Code: "ESP",
  ),
  Country(
    isoCode: "LK",
    currencyCode: "LKR",
    currencyName: "Sri Lankan rupee",
    name: "Sri Lanka",
    iso3Code: "LKA",
  ),
  Country(
    isoCode: "SD",
    currencyCode: "SDG",
    currencyName: "Sudanese pound",
    name: "Sudan",
    iso3Code: "SDN",
  ),
  Country(
    isoCode: "SR",
    currencyCode: "SRD",
    currencyName: "Surinamese dollar",
    name: "Suriname",
    iso3Code: "SUR",
  ),
  Country(
    isoCode: "SJ",
    currencyCode: "NOK",
    currencyName: "Norwegian krone",
    name: "Svalbard and Jan Mayen",
    iso3Code: "SJM",
  ),
  Country(
    isoCode: "SZ",
    currencyCode: "SZL",
    currencyName: "Swazi lilangeni",
    name: "Swaziland",
    iso3Code: "SWZ",
  ),
  Country(
    isoCode: "SE",
    currencyCode: "SEK",
    currencyName: "Swedish krona",
    name: "Sweden",
    iso3Code: "SWE",
  ),
  Country(
    isoCode: "CH",
    currencyCode: "CHF",
    currencyName: "Swiss franc",
    name: "Switzerland",
    iso3Code: "CHE",
  ),
  Country(
    isoCode: "SY",
    currencyCode: "SYP",
    currencyName: "Syrian pound",
    name: "Syrian Arab Republic",
    iso3Code: "SYR",
  ),
  Country(
    isoCode: "TW",
    currencyCode: "TWD",
    currencyName: "New Taiwan dollar",
    name: "Taiwan",
    iso3Code: "TWN",
  ),
  Country(
    isoCode: "TJ",
    currencyCode: "TJS",
    currencyName: "Tajikistani somoni",
    name: "Tajikistan",
    iso3Code: "TJK",
  ),
  Country(
    isoCode: "TZ",
    currencyCode: "TZS",
    currencyName: "Tanzanian shilling",
    name: "Tanzania, United Republic of",
    iso3Code: "TZA",
  ),
  Country(
    isoCode: "TH",
    currencyCode: "THB",
    currencyName: "Thai baht",
    name: "Thailand",
    iso3Code: "THA",
  ),
  Country(
    isoCode: "TL",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Timor-Leste",
    iso3Code: "TLS",
  ),
  Country(
    isoCode: "TG",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Togo",
    iso3Code: "TGO",
  ),
  Country(
    isoCode: "TK",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Tokelau",
    iso3Code: "TKL",
  ),
  Country(
    isoCode: "TO",
    currencyCode: "TOP",
    currencyName: "Tongan paʻanga",
    name: "Tonga",
    iso3Code: "TON",
  ),
  Country(
    isoCode: "TT",
    currencyCode: "TTD",
    currencyName: "Trinidad and Tobago dollar",
    name: "Trinidad and Tobago",
    iso3Code: "TTO",
  ),
  Country(
    isoCode: "TN",
    currencyCode: "TND",
    currencyName: "Tunisian dinar",
    name: "Tunisia",
    iso3Code: "TUN",
  ),
  Country(
    isoCode: "TR",
    currencyCode: "TRY",
    currencyName: "Turkish lira",
    name: "Turkey",
    iso3Code: "TUR",
  ),
  Country(
    isoCode: "TM",
    currencyCode: "TMT",
    currencyName: "Turkmenistan manat",
    name: "Turkmenistan",
    iso3Code: "TKM",
  ),
  Country(
    isoCode: "TC",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Turks and Caicos Islands",
    iso3Code: "TCA",
  ),
  Country(
    isoCode: "TV",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Tuvalu",
    iso3Code: "TUV",
  ),
  Country(
    isoCode: "UG",
    currencyCode: "UGX",
    currencyName: "Ugandan shilling",
    name: "Uganda",
    iso3Code: "UGA",
  ),
  Country(
    isoCode: "UA",
    currencyCode: "UAH",
    currencyName: "Ukrainian hryvnia",
    name: "Ukraine",
    iso3Code: "UKR",
  ),
  Country(
    isoCode: "AE",
    currencyCode: "AED",
    currencyName: "United Arab Emirates dirham",
    name: "United Arab Emirates",
    iso3Code: "ARE",
  ),
  Country(
    isoCode: "GB",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "United Kingdom of Great Britain and Northern Ireland",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "US",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "United States of America",
    iso3Code: "USA",
  ),
  Country(
    isoCode: "UY",
    currencyCode: "UYU",
    currencyName: "Uruguayan peso",
    name: "Uruguay",
    iso3Code: "URY",
  ),
  Country(
    isoCode: "UZ",
    currencyCode: "UZS",
    currencyName: "Uzbekistani so'm",
    name: "Uzbekistan",
    iso3Code: "UZB",
  ),
  Country(
    isoCode: "VU",
    currencyCode: "VUV",
    currencyName: "Vanuatu vatu",
    name: "Vanuatu",
    iso3Code: "VUT",
  ),
  Country(
    isoCode: "VE",
    currencyCode: "VEF",
    currencyName: "Venezuelan bolívar",
    name: "Venezuela (Bolivarian Republic of)",
    iso3Code: "VEN",
  ),
  Country(
    isoCode: "VN",
    currencyCode: "VND",
    currencyName: "Vietnamese đồng",
    name: "Viet Nam",
    iso3Code: "VNM",
  ),
  Country(
    isoCode: "WF",
    currencyCode: "XPF",
    currencyName: "CFP franc",
    name: "Wallis and Futuna",
    iso3Code: "WLF",
  ),
  Country(
    isoCode: "EH",
    currencyCode: "MAD",
    currencyName: "Moroccan dirham",
    name: "Western Sahara",
    iso3Code: "ESH",
  ),
  Country(
    isoCode: "YE",
    currencyCode: "YER",
    currencyName: "Yemeni rial",
    name: "Yemen",
    iso3Code: "YEM",
  ),
  Country(
    isoCode: "ZM",
    currencyCode: "ZMW",
    currencyName: "Zambian kwacha",
    name: "Zambia",
    iso3Code: "ZMB",
  ),
  Country(
    isoCode: "ZW",
    currencyCode: "BWP",
    currencyName: "Botswana pula",
    name: "Zimbabwe",
    iso3Code: "ZWE",
  ),
];

const List<Map<String, String>> countryList2 = [
  {"_id": "5d43e8959bf49cddde3bf9d8", "name": "Global"},
  {"_id": "5cf8b39a635e13083beadbf2", "name": "Afghanistan"},
  {"_id": "5cf8b39a635e13083beaded0", "name": "Aland Islands"},
  {"_id": "5cf8b39a635e13083beadc51", "name": "Albania"},
  {"_id": "5cf8b39f635e13083beaf590", "name": "Algeria"},
  {"_id": "5cf8b39a635e13083beaddc6", "name": "American Samoa"},
  {"_id": "5cf8b399635e13083beadbd3", "name": "Andorra"},
  {"_id": "5cf8b39a635e13083beadcb3", "name": "Angola"},
  {"_id": "5cf8b39a635e13083beadc50", "name": "Anguilla"},
  {"_id": "5cf8b39a635e13083beadce1", "name": "Antarctica"},
  {"_id": "5cf8b39a635e13083beadc46", "name": "Antigua and Barbuda"},
  {"_id": "5cf8b39a635e13083beadce2", "name": "Argentina"},
  {"_id": "5cf8b39a635e13083beadc96", "name": "Armenia"},
  {"_id": "5cf8b39a635e13083beadecf", "name": "Aruba"},
  {"_id": "5cf8b39a635e13083beaddfa", "name": "Australia"},
  {"_id": "5cf8b39a635e13083beaddcd", "name": "Austria"},
  {"_id": "5cf8b39a635e13083beadee5", "name": "Azerbaijan"},
  {"_id": "5cf8b39b635e13083beae71d", "name": "Bahamas"},
  {"_id": "5cf8b39b635e13083beae1bc", "name": "Bahrain"},
  {"_id": "5cf8b39a635e13083beadf9d", "name": "Bangladesh"},
  {"_id": "5cf8b39a635e13083beadf90", "name": "Barbados"},
  {"_id": "5cf8b39b635e13083beae77f", "name": "Belarus"},
  {"_id": "5cf8b39b635e13083beae047", "name": "Belgium"},
  {"_id": "5cf8b39c635e13083beae7b9", "name": "Belize"},
  {"_id": "5cf8b39b635e13083beae1e6", "name": "Benin"},
  {"_id": "5cf8b39b635e13083beae211", "name": "Bermuda"},
  {"_id": "5cf8b39b635e13083beae749", "name": "Bhutan"},
  {"_id": "5cf8b39b635e13083beae227", "name": "Bolivia"},
  {
    "_id": "5cf8b39b635e13083beae24c",
    "name": "Bonaire, Saint Eustatius and Saba "
  },
  {"_id": "5cf8b39a635e13083beadf6d", "name": "Bosnia and Herzegovina"},
  {"_id": "5cf8b39b635e13083beae763", "name": "Botswana"},
  {"_id": "5cf8b39b635e13083beae762", "name": "Bouvet Island"},
  {"_id": "5cf8b39b635e13083beae251", "name": "Brazil"},
  {"_id": "5cf8b3a2635e13083beb111e", "name": "British Indian Ocean Territory"},
  {"_id": "5cf8b3a8635e13083beb4b0b", "name": "British Virgin Islands"},
  {"_id": "5cf8b39b635e13083beae21e", "name": "Brunei"},
  {"_id": "5cf8b39b635e13083beae168", "name": "Bulgaria"},
  {"_id": "5cf8b39b635e13083beae10d", "name": "Burkina Faso"},
  {"_id": "5cf8b39b635e13083beae1ca", "name": "Burundi"},
  {"_id": "5cf8b3a3635e13083beb1916", "name": "Cambodia"},
  {"_id": "5cf8b39d635e13083beaea7d", "name": "Cameroon"},
  {"_id": "5cf8b39c635e13083beae7c4", "name": "Canada"},
  {"_id": "5cf8b39e635e13083beaefc6", "name": "Cape Verde"},
  {"_id": "5cf8b3a3635e13083beb1a94", "name": "Cayman Islands"},
  {"_id": "5cf8b39c635e13083beae903", "name": "Central African Republic"},
  {"_id": "5cf8b3a7635e13083beb3702", "name": "Chad"},
  {"_id": "5cf8b39d635e13083beaea0d", "name": "Chile"},
  {"_id": "5cf8b39d635e13083beaeac8", "name": "China"},
  {"_id": "5cf8b39e635e13083beaefe4", "name": "Christmas Island"},
  {"_id": "5cf8b39c635e13083beae8af", "name": "Cocos Islands"},
  {"_id": "5cf8b39d635e13083beaee09", "name": "Colombia"},
  {"_id": "5cf8b3a3635e13083beb196f", "name": "Comoros"},
  {"_id": "5cf8b39d635e13083beae9fd", "name": "Cook Islands"},
  {"_id": "5cf8b39d635e13083beaef04", "name": "Costa Rica"},
  {"_id": "5cf8b3a1635e13083beb044d", "name": "Croatia"},
  {"_id": "5cf8b39e635e13083beaef36", "name": "Cuba"},
  {"_id": "5cf8b39e635e13083beaefe3", "name": "Curaçao"},
  {"_id": "5cf8b39e635e13083beaefe5", "name": "Cyprus"},
  {"_id": "5cf8b39e635e13083beaeff3", "name": "Czech Republic"},
  {
    "_id": "5cf8b39c635e13083beae8b5",
    "name": "Democratic Republic of the Congo"
  },
  {"_id": "5cf8b39f635e13083beaf4fe", "name": "Denmark"},
  {"_id": "5cf8b39f635e13083beaf4f2", "name": "Djibouti"},
  {"_id": "5cf8b39f635e13083beaf535", "name": "Dominica"},
  {"_id": "5cf8b39f635e13083beaf541", "name": "Dominican Republic"},
  {"_id": "5cf8b3a7635e13083beb3898", "name": "East Timor"},
  {"_id": "5cf8b39f635e13083beaf6b8", "name": "Ecuador"},
  {"_id": "5cf8b39f635e13083beaf72c", "name": "Egypt"},
  {"_id": "5cf8b3a7635e13083beb365f", "name": "El Salvador"},
  {"_id": "5cf8b3a0635e13083beb02a7", "name": "Equatorial Guinea"},
  {"_id": "5cf8b39f635e13083beaf7c2", "name": "Eritrea"},
  {"_id": "5cf8b39f635e13083beaf713", "name": "Estonia"},
  {"_id": "5cf8b39f635e13083beafa4d", "name": "Ethiopia"},
  {"_id": "5f44d396f36cfa6eee54923c", "name": "European Union "},
  {"_id": "5cf8b3a0635e13083beafb0a", "name": "Falkland Islands"},
  {"_id": "5cf8b3a0635e13083beafb11", "name": "Faroe Islands"},
  {"_id": "5cf8b3a0635e13083beafb00", "name": "Fiji"},
  {"_id": "5cf8b3a0635e13083beafaa7", "name": "Finland"},
  {"_id": "5cf8b3a0635e13083beafb19", "name": "France"},
  {"_id": "5cf8b3a0635e13083beb0204", "name": "French Guiana"},
  {"_id": "5cf8b3a5635e13083beb278c", "name": "French Polynesia"},
  {"_id": "5cf8b3a7635e13083beb3733", "name": "French Southern Territories"},
  {"_id": "5cf8b3a0635e13083beafe12", "name": "Gabon"},
  {"_id": "5cf8b3a0635e13083beb025d", "name": "Gambia"},
  {"_id": "5cf8b3a0635e13083beb01e1", "name": "Georgia"},
  {"_id": "5cf8b39e635e13083beaf0c1", "name": "Germany"},
  {"_id": "5cf8b3a0635e13083beb0211", "name": "Ghana"},
  {"_id": "5cf8b3a0635e13083beb0256", "name": "Gibraltar"},
  {"_id": "5cf8b3a1635e13083beb02b4", "name": "Greece"},
  {"_id": "5cf8b3a0635e13083beb0257", "name": "Greenland"},
  {"_id": "5cf8b3a0635e13083beb01d8", "name": "Grenada"},
  {"_id": "5cf8b3a0635e13083beb02a6", "name": "Guadeloupe"},
  {"_id": "5cf8b3a1635e13083beb03cd", "name": "Guam"},
  {"_id": "5cf8b3a1635e13083beb0365", "name": "Guatemala"},
  {"_id": "5cf8b3a0635e13083beb0205", "name": "Guernsey"},
  {"_id": "5cf8b3a0635e13083beb026a", "name": "Guinea"},
  {"_id": "5cf8b3a1635e13083beb03e7", "name": "Guinea-Bissau"},
  {"_id": "5cf8b3a1635e13083beb03f6", "name": "Guyana"},
  {"_id": "5cf8b3a1635e13083beb047d", "name": "Haiti"},
  {
    "_id": "5cf8b3a1635e13083beb041d",
    "name": "Heard Island and McDonald Islands"
  },
  {"_id": "5cf8b3a1635e13083beb0422", "name": "Honduras"},
  {"_id": "5cf8b3a1635e13083beb0404", "name": "Hong Kong"},
  {"_id": "5cf8b3a1635e13083beb04a2", "name": "Hungary"},
  {"_id": "5cf8b3a2635e13083beb1260", "name": "Iceland"},
  {"_id": "5cf8b3a2635e13083beb0774", "name": "India"},
  {"_id": "5cf8b3a1635e13083beb053f", "name": "Indonesia"},
  {"_id": "5cf8b3a2635e13083beb117e", "name": "Iran"},
  {"_id": "5cf8b3a2635e13083beb1127", "name": "Iraq"},
  {"_id": "5cf8b3a1635e13083beb06db", "name": "Ireland"},
  {"_id": "5cf8b3a2635e13083beb0773", "name": "Isle of Man"},
  {"_id": "5cf8b3a1635e13083beb0724", "name": "Israel"},
  {"_id": "5cf8b3a2635e13083beb126d", "name": "Italy"},
  {"_id": "5cf8b39d635e13083beae9b0", "name": "Ivory Coast"},
  {"_id": "5cf8b3a2635e13083beb153a", "name": "Jamaica"},
  {"_id": "5cf8b3a2635e13083beb157b", "name": "Japan"},
  {"_id": "5cf8b3a2635e13083beb152c", "name": "Jersey"},
  {"_id": "5cf8b3a2635e13083beb1554", "name": "Jordan"},
  {"_id": "5cf8b3a3635e13083beb1a9d", "name": "Kazakhstan"},
  {"_id": "5cf8b3a2635e13083beb188b", "name": "Kenya"},
  {"_id": "5cf8b3a3635e13083beb1949", "name": "Kiribati"},
  {"_id": "5cf8b3a3635e13083beb1a55", "name": "Kosovo"},
  {"_id": "5cf8b3a3635e13083beb1a7c", "name": "Kuwait"},
  {"_id": "5cf8b3a2635e13083beb18f6", "name": "Kyrgyzstan"},
  {"_id": "5cf8b3a3635e13083beb1afe", "name": "Laos"},
  {"_id": "5cf8b3a3635e13083beb1c04", "name": "Latvia"},
  {"_id": "5cf8b3a3635e13083beb1b1d", "name": "Lebanon"},
  {"_id": "5cf8b3a3635e13083beb1bbc", "name": "Lesotho"},
  {"_id": "5cf8b3a3635e13083beb1ba2", "name": "Liberia"},
  {"_id": "5cf8b3a4635e13083beb1c8a", "name": "Libya"},
  {"_id": "5cf8b3a3635e13083beb1b40", "name": "Liechtenstein"},
  {"_id": "5cf8b3a3635e13083beb1bcf", "name": "Lithuania"},
  {"_id": "5cf8b3a3635e13083beb1bfd", "name": "Luxembourg"},
  {"_id": "5cf8b3a4635e13083beb1f74", "name": "Macao"},
  {"_id": "5cf8b3a4635e13083beb1e61", "name": "Macedonia"},
  {"_id": "5cf8b3a4635e13083beb1dca", "name": "Madagascar"},
  {"_id": "5cf8b3a4635e13083beb2020", "name": "Malawi"},
  {"_id": "5cf8b3a4635e13083beb22a3", "name": "Malaysia"},
  {"_id": "5cf8b3a4635e13083beb2002", "name": "Maldives"},
  {"_id": "5cf8b3a4635e13083beb1edb", "name": "Mali"},
  {"_id": "5cf8b3a4635e13083beb1f9b", "name": "Malta"},
  {"_id": "5cf8b3a4635e13083beb1e3b", "name": "Marshall Islands"},
  {"_id": "5cf8b3a4635e13083beb1f7b", "name": "Martinique"},
  {"_id": "5cf8b3a4635e13083beb1f7c", "name": "Mauritania"},
  {"_id": "5cf8b3a4635e13083beb1fe5", "name": "Mauritius"},
  {"_id": "5cf8b3a9635e13083beb4bee", "name": "Mayotte"},
  {"_id": "5cf8b3a4635e13083beb2051", "name": "Mexico"},
  {"_id": "5cf8b3a0635e13083beafb0b", "name": "Micronesia"},
  {"_id": "5cf8b3a4635e13083beb1d71", "name": "Moldova"},
  {"_id": "5cf8b3a4635e13083beb1d5f", "name": "Monaco"},
  {"_id": "5cf8b3a4635e13083beb1f48", "name": "Mongolia"},
  {"_id": "5cf8b3a4635e13083beb1dab", "name": "Montenegro"},
  {"_id": "5cf8b3a4635e13083beb1f95", "name": "Montserrat"},
  {"_id": "5cf8b3a4635e13083beb1ccb", "name": "Morocco"},
  {"_id": "5cf8b3a5635e13083beb233a", "name": "Mozambique"},
  {"_id": "5cf8b3a4635e13083beb1ef9", "name": "Myanmar"},
  {"_id": "5cf8b3a5635e13083beb235f", "name": "Namibia"},
  {"_id": "5cf8b3a5635e13083beb2675", "name": "Nauru"},
  {"_id": "5cf8b3a5635e13083beb263a", "name": "Nepal"},
  {"_id": "5cf8b3a5635e13083beb24f4", "name": "Netherlands"},
  {"_id": "5cf8b3a9635e13083beb4cff", "name": "Netherlands Antilles"},
  {"_id": "5cf8b3a5635e13083beb237c", "name": "New Caledonia"},
  {"_id": "5cf8b3a5635e13083beb2685", "name": "New Zealand"},
  {"_id": "5cf8b3a5635e13083beb24be", "name": "Nicaragua"},
  {"_id": "5cf8b3a5635e13083beb2383", "name": "Niger"},
  {"_id": "5cf8b3a5635e13083beb23a6", "name": "Nigeria"},
  {"_id": "5cf8b3a5635e13083beb2684", "name": "Niue"},
  {"_id": "5cf8b3a5635e13083beb23a5", "name": "Norfolk Island"},
  {"_id": "5cf8b3a3635e13083beb1987", "name": "North Korea"},
  {"_id": "5cf8b3a4635e13083beb1f75", "name": "Northern Mariana Islands"},
  {"_id": "5cf8b3a5635e13083beb2603", "name": "Norway"},
  {"_id": "5cf8b3a5635e13083beb26bc", "name": "Oman"},
  {"_id": "5cf8b3a5635e13083beb29c1", "name": "Pakistan"},
  {"_id": "5cf8b3a6635e13083beb2d83", "name": "Palau"},
  {"_id": "5cf8b3a6635e13083beb2cc3", "name": "Palestinian Territory"},
  {"_id": "5cf8b3a5635e13083beb26e1", "name": "Panama"},
  {"_id": "5cf8b3a5635e13083beb2795", "name": "Papua New Guinea"},
  {"_id": "5cf8b3a6635e13083beb2d95", "name": "Paraguay"},
  {"_id": "5cf8b3a5635e13083beb2706", "name": "Peru"},
  {"_id": "5cf8b3a5635e13083beb27b9", "name": "Philippines"},
  {"_id": "5cf8b3a6635e13083beb2c5e", "name": "Pitcairn"},
  {"_id": "5cf8b3a5635e13083beb2b02", "name": "Poland"},
  {"_id": "5cf8b3a6635e13083beb2cfd", "name": "Portugal"},
  {"_id": "5cf8b3a6635e13083beb2c5f", "name": "Puerto Rico"},
  {"_id": "5cf8b3a6635e13083beb2dc1", "name": "Qatar"},
  {"_id": "5cf8b39c635e13083beae929", "name": "Republic of the Congo"},
  {"_id": "5cf8b3a6635e13083beb2dce", "name": "Reunion"},
  {"_id": "5cf8b3a6635e13083beb2dcf", "name": "Romania"},
  {"_id": "5cf8b3a6635e13083beb2ece", "name": "Russia"},
  {"_id": "5cf8b3a6635e13083beb3366", "name": "Rwanda"},
  {"_id": "5cf8b39b635e13083beae210", "name": "Saint Barthélemy"},
  {"_id": "5cf8b3a6635e13083beb34b8", "name": "Saint Helena"},
  {"_id": "5cf8b3a3635e13083beb1975", "name": "Saint Kitts and Nevis"},
  {"_id": "5cf8b3a3635e13083beb1b33", "name": "Saint Lucia"},
  {"_id": "5cf8b3a4635e13083beb1dc9", "name": "Saint Martin"},
  {"_id": "5cf8b3a5635e13083beb2c5a", "name": "Saint Pierre and Miquelon"},
  {
    "_id": "5cf8b3a8635e13083beb4a7e",
    "name": "Saint Vincent and the Grenadines"
  },
  {"_id": "5cf8b3a9635e13083beb4bb3", "name": "Samoa"},
  {"_id": "5cf8b3a7635e13083beb35e9", "name": "San Marino"},
  {"_id": "5cf8b3a7635e13083beb365b", "name": "Sao Tome and Principe"},
  {"_id": "5cf8b3a6635e13083beb3377", "name": "Saudi Arabia"},
  {"_id": "5cf8b3a7635e13083beb35f4", "name": "Senegal"},
  {"_id": "5cf8b3a6635e13083beb2e7c", "name": "Serbia"},
  {"_id": "5cf8b3a9635e13083beb4cfa", "name": "Serbia and Montenegro"},
  {"_id": "5cf8b3a6635e13083beb33cd", "name": "Seychelles"},
  {"_id": "5cf8b3a7635e13083beb35da", "name": "Sierra Leone"},
  {"_id": "5cf8b3a6635e13083beb34b2", "name": "Singapore"},
  {"_id": "5cf8b3a7635e13083beb3691", "name": "Sint Maarten"},
  {"_id": "5cf8b3a7635e13083beb359d", "name": "Slovakia"},
  {"_id": "5cf8b3a6635e13083beb34bd", "name": "Slovenia"},
  {"_id": "5cf8b3a6635e13083beb33c1", "name": "Solomon Islands"},
  {"_id": "5cf8b3a7635e13083beb3620", "name": "Somalia"},
  {"_id": "5cf8b3a9635e13083beb4c03", "name": "South Africa"},
  {
    "_id": "5cf8b3a1635e13083beb0364",
    "name": "South Georgia and the South Sandwich Islands"
  },
  {"_id": "5cf8b3a3635e13083beb19cc", "name": "South Korea"},
  {"_id": "5cf8b3a6635e13083beb3429", "name": "South Sudan"},
  {"_id": "5cf8b39f635e13083beaf7cf", "name": "Spain"},
  {"_id": "5cf8b3a3635e13083beb1b4d", "name": "Sri Lanka"},
  {"_id": "5cf8b3a6635e13083beb33e8", "name": "Sudan"},
  {"_id": "5cf8b3a7635e13083beb364e", "name": "Suriname"},
  {"_id": "5cf8b3a7635e13083beb3599", "name": "Svalbard and Jan Mayen"},
  {"_id": "5cf8b3a7635e13083beb36eb", "name": "Swaziland"},
  {"_id": "5cf8b3a6635e13083beb3440", "name": "Sweden"},
  {"_id": "5cf8b39c635e13083beae942", "name": "Switzerland"},
  {"_id": "5cf8b3a7635e13083beb3692", "name": "Syria"},
  {"_id": "5cf8b3a8635e13083beb3b33", "name": "Taiwan"},
  {"_id": "5cf8b3a7635e13083beb387b", "name": "Tajikistan"},
  {"_id": "5cf8b3a8635e13083beb3b64", "name": "Tanzania"},
  {"_id": "5cf8b3a7635e13083beb3751", "name": "Thailand"},
  {"_id": "5cf8b3a7635e13083beb373a", "name": "Togo"},
  {"_id": "5cf8b3a7635e13083beb3894", "name": "Tokelau"},
  {"_id": "5cf8b3a7635e13083beb3930", "name": "Tonga"},
  {"_id": "5cf8b3a8635e13083beb3b0b", "name": "Trinidad and Tobago"},
  {"_id": "5cf8b3a7635e13083beb38cf", "name": "Tunisia"},
  {"_id": "5cf8b3a7635e13083beb3937", "name": "Turkey"},
  {"_id": "5cf8b3a7635e13083beb38b0", "name": "Turkmenistan"},
  {"_id": "5cf8b3a7635e13083beb36f3", "name": "Turks and Caicos Islands"},
  {"_id": "5cf8b3a8635e13083beb3b29", "name": "Tuvalu"},
  {"_id": "5cf8b3a8635e13083beb4b0c", "name": "U.S. Virgin Islands"},
  {"_id": "5cf8b3a8635e13083beb3d59", "name": "Uganda"},
  {"_id": "5cf8b3a8635e13083beb3c3c", "name": "Ukraine"},
  {"_id": "5cf8b39a635e13083beadbdd", "name": "United Arab Emirates"},
  {"_id": "5cf8b3a0635e13083beafe25", "name": "United Kingdom"},
  {"_id": "5cf8b3a8635e13083beb3e07", "name": "United States"},
  {
    "_id": "5cf8b3a8635e13083beb3dfd",
    "name": "United States Minor Outlying Islands"
  },
  {"_id": "5cf8b3a8635e13083beb49db", "name": "Uruguay"},
  {"_id": "5cf8b3a8635e13083beb4a0e", "name": "Uzbekistan"},
  {"_id": "5cf8b3a9635e13083beb4ba6", "name": "Vanuatu"},
  {"_id": "5cf8b3a8635e13083beb4a7d", "name": "Vatican"},
  {"_id": "5cf8b3a8635e13083beb4a87", "name": "Venezuela"},
  {"_id": "5cf8b3a8635e13083beb4b12", "name": "Vietnam"},
  {"_id": "5cf8b3a9635e13083beb4bae", "name": "Wallis and Futuna"},
  {"_id": "5cf8b39f635e13083beaf7c1", "name": "Western Sahara"},
  {"_id": "5cf8b3a9635e13083beb4bc0", "name": "Yemen"},
  {"_id": "5cf8b3a9635e13083beb4cad", "name": "Zambia"},
  {"_id": "5cf8b3a9635e13083beb4cd5", "name": "Zimbabwe"}
];

const List<String> salutationList = [
  "Mr.",
  "Mrs.",
  "Miss",
  "Dr.",
  "Ms.",
  "Prof.",
  "Rev.",
  "Lady",
  "Sir",
  "Capt.",
  "Major",
  "Lt.-Col.",
  "Col.",
  "Lady",
  "Lt.-Cmdr.",
  "The Hon.",
  "Cmdr.",
  "Flt. Lt.",
  "Brgdr.",
  "Judge",
  "Lord",
  "The Hon. Mrs",
  "Wng. Cmdr.",
  "Group Capt.",
  "Rt. Hon. Lord",
  "Revd. Father",
  "Revd Canon",
  "Maj.-Gen.",
  "Air Cdre.",
  "Viscount",
  "Dame",
  "Rear Admrl.",
  "Other"
];

const List<String> maritalStatusList = [
  'Single',
  'Married',
  'Widowed',
  'Separated',
  'Divorced'
];

const List<String> religionList = [
  'Christian',
  'Islam',
  'Atheist',
  'Hindu',
  'Buddhist',
  'Sikh',
  "Jews"
];

const List<String> occupationList = [
  "Agriculture, Food and Natural Resources",
  "Architecture and Construction",
  "Arts, Audio/Video Technology and Communications",
  "Business Management and Administration",
  "Education and Training",
  "Finance",
  "Government and Public Administration",
  "Health Science",
  "Hospitality and Tourism",
  "Human Services",
  "Information Technology",
  "Law, Public Safety, Corrections and Security",
  "Manufacturing",
  "Marketing, Sales and Service",
  "Science, Technology, Engineering and Mathematics",
  "Transportation, Distribution and Logistics"
];
